# Generated by Django 5.2.4 on 2025-07-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_app', '0002_alter_notes_category_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
